vich_uploader:
    db_driver: orm

    mappings:
        employeurimage:
            uri_prefix: '%app.path.employeurimages%'
            upload_destination: '%kernel.project_dir%/public/%app.path.employeurimages%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true
